#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@filebrowser[-1]
	add ucitrack filebrowser
	set ucitrack.@filebrowser[-1].exec='/etc/init.d/filebrowser start'
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
